### ISSUE TITLE
BadImageFormatException

### ISSUE THREAD

**Issue by zitjubiz** [lizhengzhou/SiemensDBSimulator#1]
你用的是什么版本的snap7.dll, 我换了snap7-full-1.4.2.7的dll就不行,出现
System.BadImageFormatException:试图加载格式不正确的程序。 (异常来自 HRESULT:0x8007000B)
   在 Snap7.S7Server.Srv_Create()
   在 Snap7.S7Server..ctor() 位置 d:\work\GEA2020\SiemensDBSimulator-master\SiemensSimulator\snap7.net.cs:行号 1340
   在 SiemensSimulator.Form1.Form1_Load(Object sender, EventArgs e) 位置 d:\work\GEA2020\SiemensDBSimulator-master\SiemensSimulator\Form1.cs:行号 60
   在 System.Windows.Forms.Form.OnLoad(EventArgs e)
   在 System.Windows.Forms.Form.OnCreateControl()
   在 System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   在 System.Windows.Forms.Control.CreateControl()
   在 System.Windows.Forms.Control.WmShowWindow(Message& m)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.Form.WmShowWindow(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by lizhengzhou** [comment]
我编译的 x64  版本，网上都是32位版本
